import { JSON_ACTIVITY_ORDER, JSON_ADDRESS, JSON_CLOSEDDATE, JSON_CUSTOMER, JSON_DATABASE, JSON_DELIVERTIME, JSON_EMPLOYEE, JSON_INJECTION_ORDER, JSON_ISOTOPE, JSON_RUN, JSON_SERVER_CONFIG, JSON_TRACER, JSON_TRACER_MAPPING, JSON_VIAL, PROP_LOGOUT, PROP_NAVBAR_ELEMENTS, PROP_USER, PROP_WEBSOCKET } from "./constants.js"



export function propsExtraction(props){
  const newProps = {}

  newProps[JSON_ADDRESS] = props[JSON_ADDRESS];
  newProps[JSON_DATABASE] = props[JSON_DATABASE];
  newProps[JSON_CLOSEDDATE] = props[JSON_CLOSEDDATE];
  newProps[JSON_CUSTOMER] = props[JSON_CUSTOMER];
  newProps[JSON_DELIVERTIME] = props[JSON_DELIVERTIME];
  newProps[JSON_EMPLOYEE] = props[JSON_EMPLOYEE];
  newProps[JSON_ISOTOPE] = props[JSON_ISOTOPE];
  newProps[PROP_LOGOUT] = props[PROP_LOGOUT];
  newProps[PROP_NAVBAR_ELEMENTS] = props[PROP_NAVBAR_ELEMENTS];
  newProps[JSON_ACTIVITY_ORDER] = props[JSON_ACTIVITY_ORDER];
  newProps[JSON_RUN] = props[JSON_RUN];
  newProps[JSON_INJECTION_ORDER] = props[JSON_INJECTION_ORDER];
  newProps[JSON_TRACER] = props[JSON_TRACER];
  newProps[JSON_TRACER_MAPPING] = props[JSON_TRACER_MAPPING];
  newProps[JSON_SERVER_CONFIG] = props[JSON_SERVER_CONFIG];
  newProps[JSON_VIAL] = props[JSON_VIAL];
  newProps[PROP_WEBSOCKET] = props[PROP_WEBSOCKET];
  newProps[PROP_USER] = props[PROP_USER];

  return newProps;
}