from enum import Enum, unique

##### Python Specific constants #####
# These constants are note shared with the frontend


TRACERSHOPDATABASENAME = 'TS_test'

USAGE = {
  1 : "Human",
  2 : "Dyr",
  3 : "Andet"
}

NO_TORDER_FOUND = 50
NO_ORDER_FOUND = 5

FDG_GROUP_NAME = "fdg"

SPECIAL_TRACER_GROUP_NAME = "special"

EMAIL_SENDER_ADDRESS = "no-reply-production@regionh.dk"

DATE_FORMAT = "%Y-%m-%d"
TIME_FORMAT = "%H:%M:%S"
DATETIME_FORMAT = f"{DATE_FORMAT} {TIME_FORMAT}"
JSON_DATETIME_FORMAT =f"{DATE_FORMAT}T{TIME_FORMAT}"

TIME_REGULAR_EXPRESSION = "(2[0-3]|[01]?[0-9]):([0-5][0-9]):([0-5][0-9])"
DATE_REGULAR_EXPRESSION = "\d{4}-(1[0-2]|0[1-9])-(0[1-9]|[12][0-9]|3[01])"

DATETIME_REGULAR_EXPRESSION = f"{DATE_REGULAR_EXPRESSION} {TIME_REGULAR_EXPRESSION}"
DATETIME_REGULAR_EXPRESSION_JS = f"{DATE_REGULAR_EXPRESSION}T{TIME_REGULAR_EXPRESSION}"

SQL_TABLE_REGULAR_EXPRESSION = "^[A-z0-9]+(\.[A-z0-9]+)?$"

##### Test specific Constants #####
# These keywords are only used in tests

LEGACY_TABLES = {
  "Roles",
  "TracerCustomer",
  "Tracers",
  "UserRoles",
  "Users",
  "VAL",
  "blockDeliverDate",
  "deliverTimes",
  "isotopes",
  "orders",
  "productionTimes",
  "t_orders",
  "tracer_types"
}

JAVASCRIPT_VERSION = "1.0.1" # Remember to update this to catch bugs


# Long list JSON key word used in Json messages
# These should have great overlap with the constants in production/frontend/src/lib/constants.js

AUTH_USERNAME = "username"
AUTH_PASSWORD = "password"
AUTH_DETAIL = "detail"
AUTH_IS_AUTHENTICATED = "isAuthenticated"
AUTH_USER_ID = "user_id"

# Errors string

ERROR_INVALID_AUTH = "InvalidAuth"
ERROR_INVALID_DATACLASS_TYPE = "NoDataClass"
ERROR_INVALID_JAVASCRIPT_VERSION = "InvalidJavascriptVersion"
ERROR_INVALID_MESSAGE = "InvalidMessage"
ERROR_INVALID_MESSAGE_TYPE = "InvalidMessageType"
ERROR_OBJECT_NOT_FOUND = "objectNotFound"
ERROR_NO_JAVASCRIPT_VERSION = "NoJavaScriptVersion"
ERROR_NO_MESSAGE_ID = "NoMessageID"
ERROR_NO_MESSAGE_TYPE = "NoMessageType"
ERROR_INSUFFICIENT_PERMISSIONS = "InsufficientPermissions"
ERROR_INSUFFICIENT_DATA = "InsufficientData"
ERROR_UNKNOWN_FAILURE = "unknownError"

# There is some problems regarding what the difference is between a JSON_ var and a WEBSOCKET_DATA_ constant

JSON_ACTIVITY_ORDER = "orders"
JSON_ACTIVE_DATABASE = "active_database"
JSON_ADDRESS  = "address"
JSON_AUTH = "auth"
JSON_CLOSED_DATE = "closeddate"
JSON_CUSTOMER  = "customer"
JSON_DATABASE = "database"
JSON_DEADLINE = "deadline"
JSON_DELIVER_TIME = "deliverTimes"
JSON_EMPLOYEE = "employee"
JSON_FIELD_TO_UPDATE = "FieldToUpdate"
JSON_GHOST_ORDER = "ghostOrder"
JSON_GREAT_STATE = "GREATSTATE"
JSON_INJECTION_ORDER = "t_orders"
JSON_ISOTOPE = "isotopes"
JSON_ORDERS  = "orders"
JSON_PRODUCTION = "production"
JSON_RUN = "run"
JSON_TRACER = "tracer"
JSON_TRACER_MAPPING = "tracer_mapping"
JSON_SERVER_CONFIG = "server_config"
JSON_VIAL = "vial"
JSON_SECONDARY_EMAIL = "secondaryEmail"
JSON_PROCEDURE = "procedure"
JSON_USER = "user"
JSON_USER_ASSIGNMENT = "userAssignment"
JSON_MESSAGE = "message"
JSON_MESSAGE_ASSIGNMENT = "messageAssignment"
JSON_ENDPOINT = "deliveryEndpoint"
JSON_LOCATION = "location"
JSON_BOOKING = "booking"

#Keywords
LEGACY_KEYWORD_ACTIVITY = "activity"
LEGACY_KEYWORD_ADDRESS_1 = "addr1"
LEGACY_KEYWORD_ADDRESS_2 = "addr2"
LEGACY_KEYWORD_ADDRESS_3 = "addr3"
LEGACY_KEYWORD_ADDRESS_4 = "addr4"
LEGACY_KEYWORD_AMOUNT = "amount"
LEGACY_KEYWORD_AMOUNT_O = "amount_o"
LEGACY_KEYWORD_BID = "BID"
LEGACY_KEYWORD_BATCHNR = "batchnr"
LEGACY_KEYWORD_CHARGE = "charge"
LEGACY_KEYWORD_COID = "COID"
LEGACY_KEYWORD_COMMENT = "comment"
LEGACY_KEYWORD_CONTACT = "contact"
LEGACY_KEYWORD_CUSTOMER = "customer"
LEGACY_KEYWORD_CUSTOMER_NUMBER = "kundenr"
LEGACY_KEYWORD_CUSTOMER_USERNAME = "UserName" # This exists because legacy reasons
LEGACY_KEYWORD_DAY = "day"
LEGACY_KEYWORD_DDATE = "ddate"
LEGACY_KEYWORD_DELIVER_DATETIME = "deliver_datetime"
LEGACY_KEYWORD_DELIVER_TIME = "dtime"
LEGACY_KEYWORD_DELIVER_TIME_ID = "DTID"
LEGACY_KEYWORD_EMAIL_1 = "email"
LEGACY_KEYWORD_EMAIL_2 = "email2"
LEGACY_KEYWORD_EMAIL_3 = "email3"
LEGACY_KEYWORD_EMAIL_4 = "email4"
LEGACY_KEYWORD_FILLDATE = "filldate"
LEGACY_KEYWORD_FILLTIME = "filltime"
LEGACY_KEYWORD_FREED_BY = "frigivet_af"
LEGACY_KEYWORD_FREED_AMOUNT = "frigivet_amount"
LEGACY_KEYWORD_FREED_DATETIME = "frigivet_datetime"
LEGACY_KEYWORD_HALFLIFE = "halflife"
LEGACY_KEYWORD_SMALL_ID = "id"
LEGACY_KEYWORD_ID = "ID"
LEGACY_KEYWORD_INJECTIONS = "n_injections"
LEGACY_KEYWORD_IN_USE = "in_use"
LEGACY_KEYWORD_ISOTOPE = "isotope"
LEGACY_KEYWORD_LONG_NAME = "longName"
LEGACY_KEYWORD_NAME = "name"
LEGACY_KEYWORD_OID = "oid"
LEGACY_KEYWORD_ORDER_ID = "order_id"
LEGACY_KEYWORD_ORDER_BLOCK = "order_block"
LEGACY_KEYWORD_OVERHEAD = "overhead"
LEGACY_KEYWORD_PRODUCTION_ID = "PTID"
LEGACY_KEYWORD_PRODUCTION_TIME = "ptime"
LEGACY_KEYWORD_REAL_NAME = "Realname"
LEGACY_KEYWORD_REPEAT = "repeat_t"
LEGACY_KEYWORD_RUN = "run"
LEGACY_KEYWORD_STATUS = "status"
LEGACY_KEYWORD_TELEFON_NUMBER = "tlf"
LEGACY_KEYWORD_TOTAL_AMOUNT = "total_amount"
LEGACY_KEYWORD_TOTAL_AMOUNT_O = "total_amount_o"
LEGACY_KEYWORD_TRACER = "tracer"
LEGACY_KEYWORD_TRACER_TYPE = "tracer_type"
LEGACY_KEYWORD_USAGE = "anvendelse"
LEGACY_KEYWORD_USERNAME = "UserName"
LEGACY_KEYWORD_USERNAME_ORDERS = "username"
LEGACY_KEYWORD_USERGROUP = "usergroup"
LEGACY_KEYWORD_VOLUME = "volume"

# WEBSOCKET MESSAGES
WEBSOCKET_DATA                 = "data"
WEBSOCKET_DATATYPE             = "datatype"
WEBSOCKET_DATA_ID              = "dataID"
WEBSOCKET_DATE                 = "date"
WEBSOCKET_DEAD_ORDERS          = "deadOrders"
WEBSOCKET_ERROR                = "error"
WEBSOCKET_JAVASCRIPT_VERSION   = "javascriptVersion"
WEBSOCKET_MESSAGE_ANSWER       = "answer"
WEBSOCKET_MESSAGE_AUTH_LOGIN   = "login"
WEBSOCKET_MESSAGE_AUTH_LOGOUT  = "logout"
WEBSOCKET_MESSAGE_AUTH_WHOAMI  = "whoami"
WEBSOCKET_MESSAGE_CREATE_DATA_CLASS = "createDataClass"
WEBSOCKET_MESSAGE_DELETE_DATA_CLASS = "deleteDataClass"
WEBSOCKET_MESSAGE_CREATE_ACTIVITY_ORDER = "createActivityOrder"
WEBSOCKET_MESSAGE_CREATE_INJECTION_ORDER = "createInjectionOrder"
WEBSOCKET_MESSAGE_ECHO         = "echo"
WEBSOCKET_MESSAGE_EDIT_STATE   = "editState"
WEBSOCKET_MESSAGE_EDIT_DJANGO  = "editDjango"
WEBSOCKET_MESSAGE_FREE_ACTIVITY = "freeActivity"
WEBSOCKET_MESSAGE_FREE_INJECTION = "freeInjection"
WEBSOCKET_MESSAGE_FREE_ORDER = "freeOrder"
WEBSOCKET_MESSAGE_GET_HISTORY  = "history"
WEBSOCKET_MESSAGE_GET_ORDERS   = "getOrders"
WEBSOCKET_MESSAGE_GREAT_STATE  = "getGREATState"
WEBSOCKET_MESSAGE_GET_STATE  = "getState"
WEBSOCKET_MESSAGE_ID           = "messageID"
WEBSOCKET_MESSAGE_MASS_ORDER   = "massOrder"
WEBSOCKET_MESSAGE_ORDER_ACTIVITY = "OrderActivity"
WEBSOCKET_MESSAGE_ORDER_INJECTION = "OrderInjection"
WEBSOCKET_MESSAGE_MODEL_CREATE = "createModel"
WEBSOCKET_MESSAGE_MODEL_DELETE = "deleteModel"
WEBSOCKET_MESSAGE_MODEL_EDIT   = "editModel"
WEBSOCKET_MESSAGE_MOVE_ORDERS  = "moveOrder"
WEBSOCKET_MESSAGE_RESTORE_ORDERS = "restoreOrders"
WEBSOCKET_MESSAGE_SUCCESS      = "success"
WEBSOCKET_MESSAGE_TYPE         = "messageType"
WEBSOCKET_MESSAGE_UPDATE_STATE = "updateState"
WEBSOCKET_REFRESH              = "refresh"
WEBSOCKET_SEND_EVENT           = "sendEvent"
WEBSOCKET_SESSION_ID           = "sessionid"
WEBSOCKET_EVENT_TYPE           = "type"
WEBSOCKET_UPDATE_SERVERCONFIG  = "updateServerConfig"

WEBSOCKET_MESSAGE_TYPES = [
  WEBSOCKET_MESSAGE_AUTH_LOGIN,
  WEBSOCKET_MESSAGE_AUTH_LOGOUT,
  WEBSOCKET_MESSAGE_AUTH_WHOAMI,
  WEBSOCKET_MESSAGE_CREATE_ACTIVITY_ORDER,
  WEBSOCKET_MESSAGE_CREATE_INJECTION_ORDER,
  WEBSOCKET_MESSAGE_ECHO,
  WEBSOCKET_MESSAGE_GET_ORDERS,
  WEBSOCKET_MESSAGE_GET_STATE,
  WEBSOCKET_MESSAGE_FREE_ACTIVITY,
  WEBSOCKET_MESSAGE_FREE_INJECTION,
  WEBSOCKET_MESSAGE_MODEL_CREATE,
  WEBSOCKET_MESSAGE_MODEL_DELETE,
  WEBSOCKET_MESSAGE_MODEL_EDIT,
  WEBSOCKET_MESSAGE_MASS_ORDER,
  WEBSOCKET_MESSAGE_ORDER_ACTIVITY,
  WEBSOCKET_MESSAGE_ORDER_INJECTION,
  WEBSOCKET_MESSAGE_MOVE_ORDERS,
  WEBSOCKET_MESSAGE_RESTORE_ORDERS,
]