# Generated by Django 3.0.8 on 2020-09-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=30, null=True)),
                ('port', models.CharField(max_length=6, null=True)),
                ('description', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('kundeName', models.CharField(max_length=30)),
                ('is_REGH', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PotentialUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('email_1', models.CharField(blank=True, max_length=256, null=True)),
                ('email_2', models.CharField(blank=True, max_length=256, null=True)),
                ('email_3', models.CharField(blank=True, max_length=256, null=True)),
                ('email_4', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('cityname', models.CharField(blank=True, max_length=60, null=True)),
                ('postcode', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tracer',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('tracerName', models.CharField(max_length=30, null=True, unique=True)),
                ('halfTime', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('baseDosis', models.IntegerField(null=True)),
                ('delay', models.IntegerField(default=0)),
                ('inUse', models.BooleanField(default=False)),
                ('tracer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Tracer')),
            ],
        ),
        migrations.CreateModel(
            name='KundeUsesLocation',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('kunde', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Kunde')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('databaseName', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('accessionNumber', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Location')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Procedure')),
            ],
        ),
        migrations.CreateModel(
            name='AET',
            fields=[
                ('AET', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('email_1', models.CharField(blank=True, max_length=256, null=True)),
                ('email_2', models.CharField(blank=True, max_length=256, null=True)),
                ('email_3', models.CharField(blank=True, max_length=256, null=True)),
                ('email_4', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('cityname', models.CharField(blank=True, max_length=60, null=True)),
                ('postcode', models.CharField(blank=True, max_length=30, null=True)),
                ('customer_number', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Kunde')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
