# Generated by Django 3.0.8 on 2020-08-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200820_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_number',
            field=models.IntegerField(default=0),
        ),
    ]
