CREATE TABLE VialMapping(
  Order_id INT,
  VAL_id INT UNSIGNED,
  FOREIGN KEY (Order_id) REFERENCES orders(OID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  FOREIGN KEY (VAL_id) REFERENCES VAL(ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  UNIQUE KEY (VAL_id)
);