export const customers = new Map([
  [1, {
      id : 1,
      short_name : "Customer_1",
      long_name : "Customer_long_name_1",
      dispenser_id : 1,
      billing_address : null,
      billing_city : null,
      billing_email : null,
      billing_phone : null,
      billing_zip_code : null,
      active_directory_code : null, // Drop this keyword?
  }], [2, {
      id : 2,
      short_name : "Customer_2",
      long_name : "Customer_long_name_2",
      dispenser_id : 2,
      billing_address : null,
      billing_city : null,
      billing_email : null,
      billing_phone : null,
      billing_zip_code : null,
      active_directory_code : null,
  }], [3 , {
      id : 3,
      short_name : "Customer_3",
      long_name : "Customer_long_name_3",
      dispenser_id : 3,
      billing_address : null,
      billing_city : null,
      billing_email : null,
      billing_phone : null,
      billing_zip_code : null,
      active_directory_code : null,
  }], [4 , {
      id : 4,
      short_name : "Customer_no_endpoint",
      long_name : "Customer_long_name_no_endpoint",
      dispenser_id : 3,
      billing_address : null,
      billing_city : null,
      billing_email : null,
      billing_phone : null,
      billing_zip_code : null,
      active_directory_code : null,
  }],
])