export const injection_orders = new Map([
  [1, {
      id : 1,
      delivery_time : "09:00:00",
      delivery_date : "2020-05-04",
      injections : 1,
      status : 1,
      tracer_usage : 1,
      comment : null,
      ordered_by : null,
      endpoint : 1,
      tracer : 2,
      lot_number : null,
      freed_datetime : null,
      freed_by : null,
  }], [2, {
      id : 2,
      delivery_time : "10:00:00",
      delivery_date : "2020-05-04",
      injections : 1,
      status : 2,
      tracer_usage : 1,
      comment : null,
      ordered_by : null,
      endpoint : 1,
      tracer : 2,
      lot_number : null,
      freed_datetime : null,
      freed_by : null,
  }], [3, {
      id : 3,
      delivery_time : "10:00:00",
      delivery_date : "2020-05-04",
      injections : 1,
      status : 3,
      tracer_usage : 1,
      comment : null,
      ordered_by : null,
      endpoint : 1,
      tracer : 2,
      lot_number : null,
      freed_datetime : null,
      freed_by : null,
  }],
])