export const productions = new Map([
  [1, {
      id : 1,
      production_day : 0,
      tracer : 1,
      production_time : "06:00:00",
      expiration_date : null,
  }], [2, {
      id : 2,
      production_day : 0,
      tracer : 1,
      production_time : "10:30:00",
      expiration_date : null,
  }], [3, {
      id : 3,
      production_day : 1,
      tracer : 1,
      production_time : "06:00:00",
      expiration_date : null,
  }], [4, {
      id : 4,
      production_day : 1,
      tracer : 1,
      production_time : "10:30:00",
      expiration_date : null,
  }], [5, {
      id : 5,
      production_day : 0,
      tracer : 3,
      production_time : "07:00:00",
      expiration_date : null,
  }], [6, {
      id : 6,
      production_day : 0,
      tracer : 3,
      production_time : "11:30:00",
      expiration_date : null,
  }], [7, {
    id : 7,
    production_day : 2,
    tracer : 1,
    production_time : "06:00:00",
    expiration_date : null,
  }], [8, {
    id : 8,
    production_day : 3,
    tracer : 1,
    production_time : "06:00:00",
    expiration_date : null,
  }]
]);