debug_file_log = '/home/cjen0668/work/tracershop/production/log/debug.log'
SQL_file_log = '/home/cjen0668/work/tracershop/production/log/SQL.log'
error_file_log = '/home/cjen0668/work/tracershop/production/log/error.log'
audit_file_log = '/home/cjen0668/work/tracershop/production/log/audit.log'
pingService_file_log = '/home/cjen0668/work/tracershop/production/log/pingService.log'
