from database.models import Customer, Tracer, DeliveryEndpoint

user_mapping = {
   1 :  "root",
   2 :  "fling",
   3 :  "test_kunde",
   4 :  "test_production",
   5 :  "test_transport",
   6 :  "herlev",
   7 :  "petrh",
   8 :  "gentofte",
   9 :  "glostrup",
  10 :  "hilleroed",
  11 :  "bispebjerg",
  12 :  "lund",
  13 :  "production",
  14 :  "nru",
  15 :  "aarhus",
  16 :  "goteborg",
  17 :  "odense",
  18 :  "hvidovre",
  19 :  "vejle",
  20 :  "nved",
  21 :  "petf2",
  22 :  "koge",
  23 :  "hamlet",
  24 :  "test_frigiver",
  25 :  "jacob",
  26 :  "louise",
  27 :  "anne",
  28 :  "tina",
  29 :  "malmo",
  32 :  "vibeke",
  33 :  "malene",
  30 :  "QC",
  31 :  "fu",
  44 :  "monica",
  34 :  "christina",
  35 :  "sonja",
  36 :  "ugeplan",
  37 :  "charlotte",
  38 :  "skyl",
  39 :  "kf",
  40 :  "szabolcs",
  41 :  "camilla",
  42 :  "daniel",
  43 :  "jesper",
  45 :  "life",
  46 :  "herand",
  47 :  "pet7",
  48 :  "ctn",
  49 :  "mette",
  50 :  "nic",
  51 :  "ida",
  56 :  "petq",
  52 :  "sarah",
  53 :  "ghena",
  54 :  "maria",
  55 :  "minerva",
  57 :  "kim",
  58 :  "vladimir",
}

vial_mapping = {
  1015 : "test_kunde",
  2 : "herlev",
  1 : "petrh",
  3 : "gentofte",
  4 : "glostrup",
  5 : "hilleroed",
  6 : "bispebjerg",
  7 : "lund",
  9 : "nru",
  8 : "aarhus",
  10 : "goteborg",
  11 : "odense",
  12 : "hvidovre",
  13 : "vejle",
  14 : "nved",
  16 : "petf2",
  17 : "koge",
  18 : "hamlet",
  19 : "malmo",
  99 : "QC",
  20 : "fu",
  98 : "skyl",
  15 : "kf",
  21 : "life",
  25 : "pet7",
  22 : "ctn",
  23 : "minerva",
  24 : "petq",
  99 : "QC"
}

tracer_mapping ={
  6   : Tracer.objects.get(shortname="FDG"),
  10  : Tracer.objects.get(shortname="Bonanza"),
  11  : Tracer.objects.get(shortname="NH3"),
  12  : Tracer.objects.get(shortname="PIB"),
  13  : Tracer.objects.get(shortname="H2O"),
  14  : Tracer.objects.get(shortname="FLT"),
  15  : Tracer.objects.get(shortname="CUMI"),
  16  : Tracer.objects.get(shortname="Flumazenil"),
  17  : Tracer.objects.get(shortname="DASB"),
  25  : Tracer.objects.get(shortname="PIB-Wyeth"),
  19  : Tracer.objects.get(shortname="Altanserin"),
  20  : Tracer.objects.get(shortname="Cimbi-36"),
  21  : Tracer.objects.get(shortname="Cimbi-806"),
  22  : Tracer.objects.get(shortname="Cimbi-717"),
  23  : Tracer.objects.get(shortname="SB207145"),
  26  : Tracer.objects.get(shortname="Cimbi-320"),
  27  : Tracer.objects.get(shortname="FET"),
  32  : Tracer.objects.get(shortname="Cimbi-712"),
  31  : Tracer.objects.get(shortname="NS-14492"),
  33  : Tracer.objects.get(shortname="Egis-12275"),
  34  : Tracer.objects.get(shortname="DOTATOC"),
  35  : Tracer.objects.get(shortname="PF5"),
  36  : Tracer.objects.get(shortname="AZ-10419369"),
  37  : Tracer.objects.get(shortname="Cimbi-775"),
  38  : Tracer.objects.get(shortname="BA-10"),
  39  : Tracer.objects.get(shortname="PF-55"),
  40  : Tracer.objects.get(shortname="Cimbi-366"),
  41  : Tracer.objects.get(shortname="Racloprid"),
  42  : Tracer.objects.get(shortname="Cimbi-362"),
  43  : Tracer.objects.get(shortname="Cimbi-372"),
  44  : Tracer.objects.get(shortname="Cimbi-701"),
  45  : Tracer.objects.get(shortname="2FP3"),
  103 : Tracer.objects.get(shortname="GPR17"),
  46  : Tracer.objects.get(shortname="Cimbi-92"),
  47  : Tracer.objects.get(shortname="Vortioxetine"),
  48  : Tracer.objects.get(shortname="Cimbi-150"),
  49  : Tracer.objects.get(shortname="E-55888"),
  50  : Tracer.objects.get(shortname="5-desmethyl-Cimbi-36"),
  51  : Tracer.objects.get(shortname="Pimavanserin"),
  52  : Tracer.objects.get(shortname="Cimbi-36-5"),
  53  : Tracer.objects.get(shortname="DOTA-AE105"),
  54  : Tracer.objects.get(shortname="Cimbi-422"),
  55  : Tracer.objects.get(shortname="Martinostat"),
  56  : Tracer.objects.get(shortname="Cimbi-36-2"),
  57  : Tracer.objects.get(shortname="Cimbi-416"),
  58  : Tracer.objects.get(shortname="Cimbi-198", id=46),
  59  : Tracer.objects.get(shortname="Cimbi-414"),
  60  : Tracer.objects.get(shortname="Cimbi-198", id=48),
  61  : Tracer.objects.get(shortname="HOCPCA"),
  62  : Tracer.objects.get(shortname="Cimbi-412"),
  63  : Tracer.objects.get(shortname="INP-293"),
  64  : Tracer.objects.get(shortname="INP-122"),
  65  : Tracer.objects.get(shortname="Cimbi-I293"),
  66  : Tracer.objects.get(shortname="11C-Cimbi-416"),
  67  : Tracer.objects.get(shortname="Cimbi-222", id=55),
  68  : Tracer.objects.get(shortname="Cimbi-I122"),
  69  : Tracer.objects.get(shortname="Cimbi-I334"),
  70  : Tracer.objects.get(shortname="Cimbi-418"),
  71  : Tracer.objects.get(shortname="Cimbi-222", id=59),
  72  : Tracer.objects.get(shortname="CM-418"),
  73  : Tracer.objects.get(shortname="NOTA-AE105"),
  74  : Tracer.objects.get(shortname="ACE1"),
  75  : Tracer.objects.get(shortname="NODAGA-RGD2"),
  76  : Tracer.objects.get(shortname="Cimbi-I327"),
  77  : Tracer.objects.get(shortname="Cimbi-I368"),
  78  : Tracer.objects.get(shortname="KS-29"),
  79  : Tracer.objects.get(shortname="AF76432"),
  80  : Tracer.objects.get(shortname="AF64196"),
  81  : Tracer.objects.get(shortname="Cadmium"),
  82  : Tracer.objects.get(shortname="ASEM"),
  83  : Tracer.objects.get(shortname="Cimbi-138"),
  84  : Tracer.objects.get(shortname="EE1"),
  85  : Tracer.objects.get(shortname="Fallypride"),
  86  : Tracer.objects.get(shortname="AF81905"),
  87  : Tracer.objects.get(shortname="Cimbi-I239"),
  88  : Tracer.objects.get(shortname="AF83702"),
  89  : Tracer.objects.get(shortname="Fluorid"),
  90  : Tracer.objects.get(shortname="AF87442"),
  91  : Tracer.objects.get(shortname="AF88434"),
  92  : Tracer.objects.get(shortname="AF90250"),
  93  : Tracer.objects.get(shortname="AS90250"),
  94  : Tracer.objects.get(shortname="PSMA-11"),
  95  : Tracer.objects.get(shortname="FE-PE2I"),
  96  : Tracer.objects.get(shortname="5HT2C(02311911)"),
  97  : Tracer.objects.get(shortname="SB-FE"),
  98  : Tracer.objects.get(shortname="Formaldehyd"),
  99  : Tracer.objects.get(shortname="UCB-J"),
  100 : Tracer.objects.get(shortname="ENL-10"),
  101 : Tracer.objects.get(shortname="OPS202"),
  102 : Tracer.objects.get(shortname="ASIS"),
  105 : Tracer.objects.get(shortname="MH.MZ"),
  106 : Tracer.objects.get(shortname="5-HT"),
  112 : Tracer.objects.get(shortname="DOTATATE"),
  113 : Tracer.objects.get(shortname="CRANAD"),
  114 : Tracer.objects.get(shortname="d3-MODAG001"),
  115 : Tracer.objects.get(shortname="PSMAddition"),
  116 : Tracer.objects.get(shortname="mFBG"),
  121 : Tracer.objects.get(shortname="DOTATOC(LuDo-N)"),
  122 : Tracer.objects.get(shortname="Satoreotide"),
  123 : Tracer.objects.get(shortname="FAPI-46"),
  124 : Tracer.objects.get(shortname="TRACK"),
  125 : Tracer.objects.get(shortname="PSMA-11(Arastep)"),

}

def get_customer_user(cid):
  short_name = user_mapping[cid]
  return Customer.objects.get(short_name=short_name)

def get_endpoint_for_cid(cid):
  customer = get_customer_user(cid)
  return DeliveryEndpoint.objects.get(owner=customer)


def get_vial_user(cid) -> Customer:
  if int(cid) == 99:
    return None
  return Customer.objects.get(dispenser_id=int(cid))
